### ISSUE TITLE
Duplicate parameters in generated openapi

### ISSUE THREAD

**Issue by carueda** [salvo-rs/salvo#310]
**Describe the bug**
Duplicate parameters in generated openapi, for example (as used in the [repro](https://github.com/carueda/salvo_issue)), with this endpoint:
```rust
#[endpoint(
    parameters(
        ("max_positions", description = "Maximum number of last positions to report"),
    )
)]
async fn get_foo(
    max_positions: QueryParam<usize, false>,
) -> String {
    format!(
        "max_positions = {}",
        max_positions.into_inner().unwrap_or(0),
    )
}
```
the resulting openapi contains two entries for `max_positions` as reflected in the attached screenshot.

**To Reproduce**
1. See [repro](https://github.com/carueda/salvo_issue)
4. See attached screenshot

**Expected behavior**
No duplicate parameters.

Other observed issues: The first `max_positions` entry reflected in the screenshot (which does reflect the given description) is shown as _required_, but the parameter in the function is declared as `QueryParam<usize, false>`, that is, _optional_.  Also, it is shown as _path_, but it is a _query_ parameter.

**Screenshots**
![image](https://github.com/salvo-rs/salvo/assets/556505/e83daa43-9fd4-4157-bfa3-cb031f5f86a8)

**Comment by chrislearn** [comment]
This bug is fixed, try to use latest git dependency:

```toml
[package]
name = "salvo_issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { git = "https://github.com/salvo-rs/salvo.git", features = ["oapi"] }
tokio = { version = "1", features = ["macros"] }

```
