### ISSUE TITLE
allow to remove openssl dependency by default

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#456]
By default it still takes dependency in openssl making it hard to distribute the binaries.

Suggest removing openssl by default.

```
salvo = { version = "0.58.0", default-features = false, features = ["affix", "basic-auth", "cookie", "compression", "caching-headers", "logging", "jwt-auth", "oapi", "proxy", "serve-static", "rustls"] }
```

**Comment by chrislearn** [comment]
This is current default features:

```toml
[features]
default = ["cookie", "http1", "fix-http1-request-uri", "http2", "test"]
```
