### ISSUE TITLE
Impossible to import TestClient and ResponseText

### ISSUE THREAD

**Issue by diegovinie** [salvo-rs/salvo#665]
Until version 0.61 I was able to `use salvo::test` to import *TestClient* and *ResponseText* for integration testing, however from version 0.63 to the latest (0.65) I got the following error 
```sh
error[E0432]: unresolved import `salvo::test`
 --> tests/products/mod.rs:3:12
  |
3 | use salvo::test::{ResponseExt, TestClient};
  |            ^^^^ could not find `test` in `salvo`

```

**To Reproduce**
1. create a test file `/tests/test_file.rs`
2. In `test_file.rs` import testing tools `use salvo::test::TestClient;`
3. Compile to get the error.

Personal steps to reproduce the behavior:
1. Update salvo to 0.63 (onwards)
2. run `cargo test`

**Expected behavior**
I should be able to access to the *test module* as before.

**Desktop (please complete the following information):**
- OS Linux pop-one 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux

- rustc 1.75.0 (82e1608df 2023-12-21)

- cargo.toml (dependencies)
```toml
[dependencies]
jsonwebtoken = "8.0"
salvo = {  version = "0.63.0", features = ["anyhow", "jwt-auth", "serve-static", "cors"] }
time = "0.3"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
serde = "*"
csv = "1.3.0"
thiserror = "1.0.56"
```
