### ISSUE TITLE
Server Logs Only Show HTTP/1.1 with `http2-cleartext` Feature in `salvo` Crate

### ISSUE THREAD

**Issue by TheAwiteb** [salvo-rs/salvo#851]
It seems the `http2` feature should be used instead of `http2-cleartext` for the `salvo` crate. When running the server with `http2`, the logs display `listening [HTTP/1.1] on ...`. However, changing `feature = "http2-cleartext"` to `feature = "http2"` results in the logs showing `listening [HTTP/1.1, HTTP/2.0] on ...`.

https://github.com/salvo-rs/salvo/blob/31038ed6bb67a50d67e9be9483264702216149c0/crates/core/src/conn/tcp.rs#L190-L192
And
https://github.com/salvo-rs/salvo/blob/31038ed6bb67a50d67e9be9483264702216149c0/crates/core/src/conn/unix.rs#L110-L113

**Comment by TheAwiteb** [comment]
Additionally, even when I disable the `http2` feature, the server still handles HTTP/2 requests. I don't think it should behave this way.

**Comment by chrislearn** [comment]
Could you please give me your code? The log printed by examples/tls-rustls that I tested is correct.

![image](https://github.com/user-attachments/assets/e060a08a-0bc8-47b3-b52f-2dd23a2a07f5)

**Comment by TheAwiteb** [comment]
> Could you please give me your code?

Yes, sorry for delay

**./src/main.rs:**
```rust
use salvo::prelude::*;

#[handler]
async fn hello() -> &'static str {
    "Hello World"
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().init();

    let acceptor = TcpListener::new("127.0.0.1:5800").bind().await;
    let router = Router::new().get(hello);
    tracing::info!("Server listening on http://127.0.0.1:5800");
    Server::new(acceptor).serve(router).await;
}
```

**./Cargo.toml:**
```toml
[package]
edition = "2021"
name = "test_code"
version = "0.1.0"

[dependencies]
salvo = { git = "https://github.com/salvo-rs/salvo", rev = "bdf8bd3f", package = "salvo", default-features = false, features = ["server", "http1", "http2", "http2-cleartext"]}
tokio = { version = "1.39.2", default-features = false, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
```

When I run the server, the logs show

![image](https://github.com/user-attachments/assets/2ce46bfb-2279-4e3a-a238-169f564c8e49)

However, the server supports http2 as you can see below.

![image](https://github.com/user-attachments/assets/525f20bf-d93a-41c5-add9-b9ea9d9cdaea)
